### ISSUE TITLE
Provide the ability to create a study with Eligibility requirements

### ISSUE THREAD

**Issue by benmatselby** [benmatselby/prolificli#24]
Currently, the create study functionality doesn't cater for eligibility requirements. Understand the [docs](https://docs.prolific.co/docs/api-docs/public/#tag/Studies/paths/~1api~1v1~1studies~1/post) to figure out how we can cleanly add requirements.

**Comment by Kodiologist** [comment]
Here's a working example in Python, in case it's helpful. The interface for eligibility requirements is a bit odd and the documentation isn't as helpful as it could be.

https://github.com/Kodiologist/Artiruno-task/blob/83eae6729dd34fc3ee15c16b71a71ecbc165dafa/prolific.py
