### ISSUE TITLE
Cryptic behavior when environment variables are unset

### ISSUE THREAD

**Issue by Kodiologist** [benmatselby/prolificli#68]
If `PROLIFIC_URL` is unset, the program says `Error: unable to fulfil request /api/v1/studies/?all=1: Get "/api/v1/studies/?all=1": unsupported protocol scheme ""`, which isn't a very strong hint as to what's wrong. If `PROLIFIC_URL` is set and `PROLIFIC_TOKEN` is unset, then `prolificli studies` shows no studies, without an error message.

More generally, it might not make sense to use environment variables for these things, considering that there's also a configuration file, and environment variables can be seen by other users on the same machine, if I recall correctly. `PROLIFIC_URL` can probably be hard-coded, or at least a default value can be hard-coded.

**Comment by benmatselby** [comment]
Fair points, @Kodiologist - I'll take a look. I agree that we can have a default for the URL. I'm less keen on having the token in a configuration file. I'll have a think.

**Comment by Kodiologist** [comment]
To be honest, I put a lot of passwords and API tokens in environment variables in my own code, but that's for stuff like NASA Earthdata, where it doesn't matter if somebody else gets hold of your credentials; the worst they can do is request data files while pretending to be you. In the case of Prolific, somebody with your credentials could spend your credits.

**Comment by benmatselby** [comment]
Out of interest, @Kodiologist, how would you like to present your token?

**Comment by Kodiologist** [comment]
I think a file makes sense, either the configuration file or a separate file. I know some programs for dealing with web interfaces use some kind of system keyring (like Freedesktop's Secret Service), but I don't recommend that. It's a mess.

Full disclosure, I'll probably be programming against the API directly in Python rather than using your program because I think I need #24. I'd consider writing a patch for that, but I don't speak Go (and I don't get a good impression of the language).

**Comment by Kodiologist** [comment]
That said, overall, I'm positively impressed with this program and I look forward to seeing it mature.
