### ISSUE TITLE
Inaccuracies in `prolificli study view`

### ISSUE THREAD

**Issue by Kodiologist** [benmatselby/prolificli#69]
I have a study with a reward of 1 USD, but it displays as `Reward: £1.00`. Also, the study has a prescreen criterion (`First Language` must be `English`), but `study view` says "No eligibility requirements are defined for this study."

**Comment by benmatselby** [comment]
Thanks for raising, @Kodiologist. I'll take a look.

**Comment by benmatselby** [comment]
Hey @Kodiologist 

I've done a little digging into this, and this has identified (I think) the fact we (Prolific) need to change some of the APIs internally to deliver what is required here. Here's an overview:

- In the single API call to get a study, we are missing a field called `presentment_currency_code`. This is present in the list view API call. This application defaults to `GBP` if this value is not found.
- The eligibility requirements are structured slightly differently between the list/single views of the study API. There is not a decent programmatic way to show this information. Interestingly, if you run the interactive view of study in `prolificli` it uses the data from the list view, and it will show you the eligibility records used.

I will keep this ticket open, but that's where I am currently at.

**Comment by benmatselby** [comment]
I've put in a partial fix for the currency code issue, and [released 0.0.14](https://github.com/benmatselby/prolificli/releases/tag/v0.0.14)

**Comment by Kodiologist** [comment]
I see. If you maintain the backend at Prolific, too, then I guess the smart thing to do is to make the single view and list view as similar as possible.

**Comment by benmatselby** [comment]
That's the plan. I've raised this with my team, as something we should look into. My view aligns with yours on this. :)
